baseurl = "https://keeler.github.io"
languageCode = "en"
title = "Keeler Russell"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/keeler\">Keeler Russell</a> 2019"
# disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 10
enableRobotsTXT = true
enableEmoji = true

PygmentsCodeFences = true
PygmentsStyle = "trac"

[params.sections_left]
  "about" = "About"
  "posts/" = "Blog"
  "tags" = "Tags"

# [params.features]
# disqusOnDemand = true  # Load Disqus comments on click

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.social]
twitter = ""
github = "keeler"
email = "keeler.russell@gmail.com"
linkedin = ""
gitlab = ""
instagram = ""
codepen = ""
facebook = ""

[params.social.config]
#platforms = ["twitter","github","email","linkedin","gitlab"]
platforms = ["github", "email"]

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
